# Generated by Django 4.1 on 2022-09-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SusFood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='minutes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AddField(
            model_name='carousel',
            name='sustainability',
            field=models.IntegerField(default='10'),
        ),
    ]
